### PR TITLE
012/master

### PR DESCRIPTION
**Pull request by payne-chris-r**
Updates for talk tomorrow.

### CODE REVIEW

**Comment by gaand** [comment]
I am unopposed.

**Comment by payne-chris-r** [comment]
@gaand does that mean I should merge, or wait for @jrhorn424 to give the 'ok' as well?

**Comment by gaand** [comment]
It meant I was okay with you merging.  I'm unsure of how you're coordinating with Jeff, so I didn't want to merge it myself.

**Comment by payne-chris-r** [comment]
Yes @J-Weeks. Pls merge.

**Pull request merged**
