### PR TITLE
016/solution

### PR DESCRIPTION
**Pull request by raq929**
Please rename `016/solution` to `solution` and push.

### CODE REVIEW

**Review by BenGitsCode — APPROVED** [review]
I'm not convinced that Zebras are ridable, but the tests pass. 

You pointed this into `015/solution`, was that intentional, because there isn't yet a solution branch? It makes sense to merge this into 15 and rename it to solution, but I just wanted to confirm before doing that.

**Comment by jrhorn424** [comment]
>You pointed this into 015/solution, was that intentional, because there isn't yet a solution branch? It makes sense to merge this into 15 and rename it to solution, but I just wanted to confirm before doing that.

I'll do this, not because you were wrong to hold off, but because my second pair of eyes agrees this is the right action.

**Comment by jrhorn424** [comment]
This solution is updated, except there are no solutions for `equine` available. @raq929 I'll merge. Will you open a PR with your training branch after delivery? Thanks.

**Comment by jrhorn424** [comment]
> This solution is updated, except there are no solutions for equine available... Will you open a PR with your training branch after delivery?

Oh, I retract this. I see that it is a *minimally* passing solution. I neglected to diff it against starter code. :+1:

**Pull request closed without merging**
